[versions]
managed-spring-boot = "3.2.3"
managed-spring = "6.1.4"

groovy = "4.0.18"
h2 = '2.2.224'

micronaut = "4.3.9"
micronaut-docs = "2.0.0"
micronaut-test = "4.2.0"
micronaut-cache = "4.2.2"
micronaut-views = "5.1.0"
micronaut-validation = "4.4.3"
micronaut-servlet = "4.5.0"

[libraries]
# Micronaut
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-views = { module = "io.micronaut.views:micronaut-views-bom", version.ref = "micronaut-views" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-servlet = { module = "io.micronaut.servlet:micronaut-servlet-bom", version.ref = "micronaut-servlet" }

managed-spring-boot = { module = 'org.springframework.boot:spring-boot', version.ref = 'managed-spring-boot' }
managed-spring-boot-starter = { module = 'org.springframework.boot:spring-boot-starter', version.ref = 'managed-spring-boot' }
managed-spring-boot-starter-web = { module = 'org.springframework.boot:spring-boot-starter-web', version.ref = 'managed-spring-boot' }

managed-spring = { module = 'org.springframework:spring-core', version.ref = 'managed-spring' }
managed-spring-context = { module = 'org.springframework:spring-context', version.ref = 'managed-spring' }
managed-spring-tx = { module = 'org.springframework:spring-tx', version.ref = 'managed-spring' }
managed-spring-orm = { module = 'org.springframework:spring-orm', version.ref = 'managed-spring' }
managed-spring-jdbc = { module = 'org.springframework:spring-jdbc', version.ref = 'managed-spring' }

boms-spring = { module = 'org.springframework:spring-framework-bom', version.ref = 'managed-spring' }
spring-web = { module = 'org.springframework:spring-web' }

spring-boot-actuator = { module = 'org.springframework.boot:spring-boot-actuator', version.ref = 'managed-spring-boot' }
spring-boot-autoconfigure = { module = 'org.springframework.boot:spring-boot-autoconfigure', version.ref = 'managed-spring-boot' }
spring-boot-starter-thymeleaf = { module = 'org.springframework.boot:spring-boot-starter-thymeleaf', version.ref = 'managed-spring-boot' }
spring-boot-starter-tomcat = { module = 'org.springframework.boot:spring-boot-starter-tomcat', version.ref = 'managed-spring-boot' }
spring-boot-test = { module = 'org.springframework.boot:spring-boot-starter-test', version.ref = 'managed-spring-boot' }

spring-test = { module = 'org.springframework:spring-test', version.ref = 'managed-spring' }

spock-spring = { module = 'org.spockframework:spock-spring' }

h2database = { module = 'com.h2database:h2', version.ref = 'h2' }
